### ISSUE TITLE
Bootstrap toggle initiated twice

### ISSUE THREAD

**Issue by Quezler** [rhyek/vue-bootstrap-toggle#2]
Bootstrap toggle can load twice.

Related #1

**Comment by Quezler** [comment]
Hang on, isn't [this](https://github.com/rhyek/vue-bootstrap-toggle/blob/master/src/index.vue#L7) run while compiling and not in the actual browser? that might be the cause?

**Comment by rhyek** [comment]
Sure, the `require` function is transformed to something else by `webpack`, but the module still is only imported if the condition passes.

**Comment by rhyek** [comment]
I just ran a couple of tests. This only happens in the following scenarios:
* You have a script tag loading `bootstrap-toggle.js` *after* you've loaded your `app.js`.
* You have a script tag loading `bootstrap-toggle.js` *before* your `app.js`, but you *also* have `jQuery` loaded twice. This could happen when having a script tag loading it and also having it as a dependency in your `app.js`. When this happens, the check I'm doing [here](https://github.com/rhyek/vue-bootstrap-toggle/blob/master/src/index.vue#L7) will always return false and load `bootstrap-toggle` a second time. Otherwise, the check does it's job.

In general, you should never include `bootstrap-toggle.js` *anywhere* in your code.

I'm going to close this as I feel I can't really do anything here. This is more an issue of having well organized dependencies in the project.

Let me know if there's any other way I can help you!

**Comment by Quezler** [comment]
Primary problem is that many projects/plugins/libraries often[ directly ask you ](http://www.bootstraptoggle.com/) to place it in the html file.

**Comment by rhyek** [comment]
It is understood that wrappers for use in popular JS frameworks will generally already include those dependencies for you under the hood.

**Comment by Quezler** [comment]
But for example in the case of bootstrap-toggle, you put the css and javascript in the site and it works.

Then you try e.g. this wrapper, and the previously added elements can be easily forgotten or overseen.

**Comment by rhyek** [comment]
> This is more an issue of having well organized dependencies in the project.
